# <center> Types of Variable in R </center>

In [1]:
# Character classes

colors <- c("red", "green", "blue")
colors
class(colors)

[1] "red"   "green" "blue"

[1] "character"

In [2]:
# Factor  classes

colors_f <- factor("red", "green", "blue")
print(colors_f)
class(colors_f)

[1] <NA>
Levels: blue


[1] "factor"

In [3]:
# Numeric classes

num <- c(1,2,3,4,5)
print(num)
class(num)

[1] 1 2 3 4 5


[1] "numeric"

In [4]:
# Integer classes

int <- c(1L, 2L, 3L)
int
class(int)

[1] 1 2 3

[1] "integer"

# <center>Data Structures in R</center>

# Vector 

In [5]:
x <- c(1,2,3,4)
x
y <- c(11,23,34,121)
y
z <- c(5,3,1, NA)
z

[1] 1 2 3 4

[1]  11  23  34 121

[1]  5  3  1 NA

In [6]:
intger_value <- c(1L, 2L, 3L, 4L)
intger_value
number_value <- c(1.1, 2.5, 3.4)
number_value
character_value <- c("min", "median", "mode")
character_value
factor_var  <- factor(c("MA", "MA", "CT", "ME"), levels = c("CT", "ME", "MA", "NH", "RI", "VT"))
print(factor_var)

[1] 1 2 3 4

[1] 1.1 2.5 3.4

[1] "min"    "median" "mode"

[1] MA MA CT ME
Levels: CT ME MA NH RI VT


In [7]:
# For logical vectors, you can use T or TRUE and F or FALSE.  
logical_var <- c(TRUE, FALSE, T, F)
logical_var

[1]  TRUE FALSE  TRUE FALSE

In [8]:
# Individual elements in R are saved as atomic vectors of length 1. 
m <- 365
typeof(m)
length(m)

[1] "double"

[1] 1

In [9]:
# To create an empty vector, use the vector(type, length) command
emp_var <- c("integer", 5)
emp_var

[1] "integer" "5"

In [10]:
# If elements are of a different type, R will coerce the vector to the most flexible type. 

coe_var <- c(5L, 3.5, "A")
coe_var
typeof(coe_var)

coe_var2 <- c(TRUE, FALSE, 46)
coe_var2
typeof(coe_var2)

[1] "5"   "3.5" "A"

[1] "character"

[1]  1  0 46

[1] "double"

In [11]:
# You can use the c() function to combine multiple vectors into one.
x_y <- c(x, y)
x_y

[1]   1   2   3   4  11  23  34 121

In [12]:
# To access elements of a vector, declare an index inside a []
x_y[5]
x_y[c(4,6)]
x_y[c(4:8)]

[1] 11

[1]  4 23

[1]   4  11  23  34 121

In [13]:
# If you try to access an element that does not exit, R will return NA.
x_y[22]

[1] NA

In [14]:
# Remove elements of a vector by using negative numbers for indexing
x_y
x_y[-8] #Remove the 8th element 
x_y #The vector still has the 8th element! 
x_y <- x_y[-8] #You need to tell R to save the new information.
x_y # Updated one

[1]   1   2   3   4  11  23  34 121

[1]  1  2  3  4 11 23 34

[1]   1   2   3   4  11  23  34 121

[1]  1  2  3  4 11 23 34

In [15]:
# Replace the 2nd element of the vector emp_var with a number.
x_y
x_y[2] = 10
x_y

[1]  1  2  3  4 11 23 34

[1]  1 10  3  4 11 23 34

In [16]:
# Replace all elements that are < 4 with the number 2
x_y[x_y < 4] <- 5
x_y

[1]  5 10  5  4 11 23 34

# Matrix

In [17]:
# We can create a Matrix using the matrix() function.
# If we don't provide number of column. R will create a matrix 1 column and multiple rows.

mat_var <- matrix(1:6)
print(mat_var)

     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4
[5,]    5
[6,]    6


In [18]:
# You can  specify the number of rows and columns for the matrix 
mat_var <- matrix(1:6, nrow=3, ncol=2)
print(mat_var)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [19]:
# Matrices are constructed column wise. If we want to construct a matrix
# row wise, set the argument byrow = TRUE. 

mat_var = matrix(1:6, nrow=3, ncol=2, byrow=TRUE)
print(mat_var)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6


In [20]:
typeof(mat_var)
length(mat_var)
class(mat_var)
attributes(mat_var)

[1] "integer"

[1] 6

[1] "matrix" "array"

$dim
[1] 3 2

In [21]:
# To add rows or columns to a matrix use the rbind() and cbind() functions.

mat_var2 <- rbind(mat_var, c(7,8))
print(mat_var2)
mat_var3 <- cbind(mat_var2, c(11, 12, 13, 14))
print(mat_var3)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8
     [,1] [,2] [,3]
[1,]    1    2   11
[2,]    3    4   12
[3,]    5    6   13
[4,]    7    8   14


In [22]:
# To access elements of a matrix, declare the index of the row and the column inside a []. 

mat_var3[2, 2] #Element in the 2nd row and the 2nd column
mat_var3[c(3, 4), 2]

[1] 4

[1] 6 8

In [23]:
# If a field inside the bracket is empty, R will select all those elements.
mat_var3[ , 3]

[1] 11 12 13 14

In [24]:
# To exclude columns or rows, use a negative index inside []
print(mat_var3[-2, ])  # Here it removes the first column

     [,1] [,2] [,3]
[1,]    1    2   11
[2,]    5    6   13
[3,]    7    8   14


In [25]:
# To assign a name to the rows and columns of a matrix, use the rownames() and colnames() functions.

rownames(mat_var3) <- c("row1", "row2", "row3", "row4")
colnames(mat_var3) <- c("column1", "column2", "column3")
mat_var3

column1 column2 column3
row1 1       2       11     
row2 3       4       12     
row3 5       6       13     
row4 7       8       14

In [26]:
# Just like with vectors, we can replace specific elements of a matrix with an assignment statement. 

mat_var2[2,2] <- 10
print(mat_var2)

     [,1] [,2]
[1,]    1    2
[2,]    3   10
[3,]    5    6
[4,]    7    8


# Array

In [27]:
# Creating an array

array1 <- array(c(1:27), dim=c(3,3,3), dimnames= list(c("r1", "r2", "r3"), c("c1", "c2", "c3"), c("m1", "m2", "m3") ))
print(array1)

, , m1

   c1 c2 c3
r1  1  4  7
r2  2  5  8
r3  3  6  9

, , m2

   c1 c2 c3
r1 10 13 16
r2 11 14 17
r3 12 15 18

, , m3

   c1 c2 c3
r1 19 22 25
r2 20 23 26
r3 21 24 27



In [28]:
# Differently using dimnames() function

array2 <- array(c(1:18), dim=c(2,3,3))
print(array2)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18



In [29]:
# Indexing array in R

array2[ , , 2] # First Matrix
array2[ 1, 3, 2] # 1st row, 3rd Column for 2rd Matrix
print( array1[c(1,2),c(2,3),c(1,2)] ) # first and second row, second and third column of first and second matrices

[,1] [,2] [,3]
[1,] 7     9   11  
[2,] 8    10   12

[1] 11

, , m1

   c2 c3
r1  4  7
r2  5  8

, , m2

   c2 c3
r1 13 16
r2 14 17



In [30]:
array1[1:2,1:2,2] # 1st two rows and columns of 2nd matrix
print(array1[-1,-3,-2]) # remove first row, third column and second matrix of array1

c1 c2
r1 10 13
r2 11 14

, , m1

   c1 c2
r2  2  5
r3  3  6

, , m3

   c1 c2
r2 20 23
r3 21 24



In [31]:
# first and third row, second and third column of first and second matrix of array1

print(array1[c(T,F,T), c(F,T,T), c(T,T,F)])

"Using Character Vectors"
print(array1[c("r1", "r3"), c("c2", "c3"), c("m1", "m2")])

, , m1

   c2 c3
r1  4  7
r3  6  9

, , m2

   c2 c3
r1 13 16
r3 15 18



[1] "Using Character Vectors"

, , m1

   c2 c3
r1  4  7
r3  6  9

, , m2

   c2 c3
r1 13 16
r3 15 18



In [32]:
# Re-assignment to change specific values of an array

print(array1)
# Change the values of the 1st row of 1st matrix
array1[1, , 1] <- c(4,4,4)
"Array1 Value"
print(array1)

, , m1

   c1 c2 c3
r1  1  4  7
r2  2  5  8
r3  3  6  9

, , m2

   c1 c2 c3
r1 10 13 16
r2 11 14 17
r3 12 15 18

, , m3

   c1 c2 c3
r1 19 22 25
r2 20 23 26
r3 21 24 27



[1] "Array1 Value"

, , m1

   c1 c2 c3
r1  4  4  4
r2  2  5  8
r3  3  6  9

, , m2

   c1 c2 c3
r1 10 13 16
r2 11 14 17
r3 12 15 18

, , m3

   c1 c2 c3
r1 19 22 25
r2 20 23 26
r3 21 24 27



In [33]:
# Arithmetic Operations of Array in R

test_array1 <- array(c(1:8), c(2,2,2))
test_array2 <- array(c(9:16), c(2,2,2))
"Array 1"
print(test_array1)
"Array 2"
print(test_array2)

[1] "Array 1"

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8



[1] "Array 2"

, , 1

     [,1] [,2]
[1,]    9   11
[2,]   10   12

, , 2

     [,1] [,2]
[1,]   13   15
[2,]   14   16



In [34]:
# Addition
array_addition = test_array1 + test_array2
print(array_addition)

, , 1

     [,1] [,2]
[1,]   10   14
[2,]   12   16

, , 2

     [,1] [,2]
[1,]   18   22
[2,]   20   24



In [35]:
# Subtraction
array_subtraction = test_array1 - test_array2
print(array_subtraction)

, , 1

     [,1] [,2]
[1,]   -8   -8
[2,]   -8   -8

, , 2

     [,1] [,2]
[1,]   -8   -8
[2,]   -8   -8



In [36]:
# Multiplication
array_multiplication = test_array1 * test_array2
print(array_multiplication)

, , 1

     [,1] [,2]
[1,]    9   33
[2,]   20   48

, , 2

     [,1] [,2]
[1,]   65  105
[2,]   84  128



In [37]:
#Division
array_division = test_array1 / test_array2
print(array_division)

, , 1

          [,1]      [,2]
[1,] 0.1111111 0.2727273
[2,] 0.2000000 0.3333333

, , 2

          [,1]      [,2]
[1,] 0.3846154 0.4666667
[2,] 0.4285714 0.5000000



In [38]:
# Taking Power
taking_power = test_array1 ^ 2
print(taking_power)

, , 1

     [,1] [,2]
[1,]    1    9
[2,]    4   16

, , 2

     [,1] [,2]
[1,]   25   49
[2,]   36   64



# Factors

In [39]:
factor1 <- factor(x = c("Male", "Female", "Female", "Male", "Female", "Male"))
print(factor1)
typeof(factor1)
str(factor1)

[1] Male   Female Female Male   Female Male  
Levels: Female Male


[1] "integer"

 Factor w/ 2 levels "Female","Male": 2 1 1 2 1 2


In [40]:
print(factor1[1])
factor1[6] <- "Female"
print(factor1)

[1] Male
Levels: Female Male
[1] Male   Female Female Male   Female Female
Levels: Female Male


In [41]:
factor2 <- factor(x = c("Female", "Male", "Male", "Female", "Male", "Female"))
print(factor2)
''
factor3 <- factor(x = c("Dog", "Cat", "Apple", "Elephent", "Ball"))
print(factor3)
str(factor3)

[1] Female Male   Male   Female Male   Female
Levels: Female Male


[1] ""

[1] Dog      Cat      Apple    Elephent Ball    
Levels: Apple Ball Cat Dog Elephent
 Factor w/ 5 levels "Apple","Ball",..: 4 3 1 5 2


In [42]:
# Without defining levels, R orderes the levels alphabetically considering as nominal variable

factor4 <- factor(x = c("Male", "Female", "Female", "Male", "Female", "Male"), levels = c("Male", "Female"))
print(factor4)
typeof(factor4)
str(factor4)

[1] Male   Female Female Male   Female Male  
Levels: Male Female


[1] "integer"

 Factor w/ 2 levels "Male","Female": 1 2 2 1 2 1


In [43]:
# Change the Specific Value

factor5<- factor(x = c("Male", "Female", "Female", "Male", "Female", "Male"), levels = c("Male", "Female", "Other"))
print(factor5)
''
factor5[6]<- "Other"
print(factor5)
str(factor5)

[1] Male   Female Female Male   Female Male  
Levels: Male Female Other


[1] ""

[1] Male   Female Female Male   Female Other 
Levels: Male Female Other
 Factor w/ 3 levels "Male","Female",..: 1 2 2 1 2 3


In [44]:
# Ordinal Variables as Factor

temperature <- factor(x = c("High", "Low", "Low", "High", "Medium"), ordered=TRUE, levels = c("Low", "Medium", "High"))
print(temperature)
str(temperature)

[1] High   Low    Low    High   Medium
Levels: Low < Medium < High
 Ord.factor w/ 3 levels "Low"<"Medium"<..: 3 1 1 3 2


In [45]:
#Renaming Factor labels

factor6 <- factor(x= c("Male", "Female", "Female", "Male", "Female", "Male"), levels= c("Male", "Female"), labels= c("M", "F"))
print(factor6)

[1] M F F M F M
Levels: M F


In [46]:
factor7 <- factor(x= c(1,1,2,2,2,1))
print(factor7)

[1] 1 1 2 2 2 1
Levels: 1 2


In [47]:
factor8 <- factor(x= c(1,1,2,2,2,1), levels= c("Male", "Female"))
print(factor8)
''
factor9 <- factor(x= c(1,1,2,2,2,1), labels= c("Male", "Female"))
print(factor9)

[1] <NA> <NA> <NA> <NA> <NA> <NA>
Levels: Male Female


[1] ""

[1] Male   Male   Female Female Female Male  
Levels: Male Female


In [48]:
factor10 <- factor(x= c("Male", "Female", "Female", "Male", "Female", "Male"), levels= c("Male", "Female"), labels= c(1, 2))
print(factor10)

[1] 1 2 2 1 2 1
Levels: 1 2


In [49]:
# Convert binary factor levels to '0' and '1'

binary_gender <- c("Male", "Female")
as.factor(binary_gender)
contrasts(as.factor(binary_gender))

[1] Male   Female
Levels: Female Male

Male
Female 0   
Male   1

In [50]:
binary1 <- contrasts(factor(binary_gender, levels= c("Male", "Female")))
binary1

Female
Male   0     
Female 1

# Data Frames

In [51]:
# We can create a data frame using the data.frame() function.

x <- c(2,5,3,6,1,6,2,3,1,5)
y <- c(54, 14, 72, 22, 52, 83, 12, 16, 93, 22)
df <- data.frame(x, y)
print(df)

   x  y
1  2 54
2  5 14
3  3 72
4  6 22
5  1 52
6  6 83
7  2 12
8  3 16
9  1 93
10 5 22


In [52]:
# Get the number of rows and Number of column

ncol(df)
nrow(df)

[1] 2

[1] 10

In [53]:
# To add columns to a data frame use the cbind() function. 

df <- cbind(df, NewCol= c(TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE ))
df

x y  NewCol
1  2 54  TRUE 
2  5 14 FALSE 
3  3 72 FALSE 
4  6 22  TRUE 
5  1 52 FALSE 
6  6 83 FALSE 
7  2 12  TRUE 
8  3 16 FALSE 
9  1 93 FALSE 
10 5 22  TRUE

In [54]:
# To add rows to a data frame use the rbind() function. We must specify the number of columns

df <- rbind(df, data.frame(x= 6, y= 99, NewCol=TRUE))
df

class(df)
typeof(df)

x y  NewCol
1  2 54  TRUE 
2  5 14 FALSE 
3  3 72 FALSE 
4  6 22  TRUE 
5  1 52 FALSE 
6  6 83 FALSE 
7  2 12  TRUE 
8  3 16 FALSE 
9  1 93 FALSE 
10 5 22  TRUE 
11 6 99  TRUE

[1] "data.frame"

[1] "list"

In [55]:
# We can also add columns to a data frame using the $. 

df$z <- c(10:20)
df

x y  NewCol z 
1  2 54  TRUE  10
2  5 14 FALSE  11
3  3 72 FALSE  12
4  6 22  TRUE  13
5  1 52 FALSE  14
6  6 83 FALSE  15
7  2 12  TRUE  16
8  3 16 FALSE  17
9  1 93 FALSE  18
10 5 22  TRUE  19
11 6 99  TRUE  20

In [56]:
# Use [[]] to access a column of a data frame by its position and $ to access it by its name. 

# Access the Column 1
df[[1]]
df[[1]][2]
df$z
df$z[1]

[1] 2 5 3 6 1 6 2 3 1 5 6

[1] 5

[1] 10 11 12 13 14 15 16 17 18 19 20

[1] 10

In [57]:
# Just like a matrix, access elements by declaring the index of the row and the column inside a []. 

'All rows, column 1: '
df[, 1]  
'All rows, column 1 and 4:'
df[, c(1, 4)]
'Row 2, columns 1 and 3:'
df[2, c(1, 3)]
'Row 2, all columns:'
df[2, ]

[1] "All rows, column 1: "

[1] 2 5 3 6 1 6 2 3 1 5 6

[1] "All rows, column 1 and 4:"

x z 
1  2 10
2  5 11
3  3 12
4  6 13
5  1 14
6  6 15
7  2 16
8  3 17
9  1 18
10 5 19
11 6 20

[1] "Row 2, columns 1 and 3:"

x NewCol
2 5 FALSE

[1] "Row 2, all columns:"

x y  NewCol z 
2 5 14 FALSE  11

# List in R

In [58]:
# Create a list in R
list1 <- list(name="Dotlab", wife="Luna", no_of_child=2, child_age=c(4, 7))
list1

$name
[1] "Dotlab"

$wife
[1] "Luna"

$no_of_child
[1] 2

$child_age
[1] 4 7

In [59]:
# Components are always numbered and may always be referred to as such order.

list1[[2]]
list1[[3]]
''
list1$name
list1$wife

[1] "Luna"

[1] 2

[1] ""

[1] "Dotlab"

[1] "Luna"

In [60]:
# List1[[4]] is a vector subscripted array then its first entry is:
list1[[4]][1]
list1$child_age[2]

[1] 4

[1] 7

In [61]:
# Concatenating lists: listname <- c(list1, list2, list3, ....)
z <- list(play= c("Cricket", "Football", "Badminton"), batch=3, subtype= c("A", "B", "C"))

combine_list <- c(list1, z)
print(combine_list)

$name
[1] "Dotlab"

$wife
[1] "Luna"

$no_of_child
[1] 2

$child_age
[1] 4 7

$play
[1] "Cricket"   "Football"  "Badminton"

$batch
[1] 3

$subtype
[1] "A" "B" "C"



In [62]:
# Create a list containing a vector, a matrix and a list.

list2 <- list(c("Jan", "Feb", "Mar"), matrix(c(1,2,3,4,5,6), nrow=2), list("Yellow", 12.2))
print(list2)

[[1]]
[1] "Jan" "Feb" "Mar"

[[2]]
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

[[3]]
[[3]][[1]]
[1] "Yellow"

[[3]][[2]]
[1] 12.2




In [63]:
# Give names to the elements in the list.
names(list2) <- c("A First Quarter", "A Matrix", "A Inner List")
list2

$`A First Quarter`
[1] "Jan" "Feb" "Mar"

$`A Matrix`
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

$`A Inner List`
$`A Inner List`[[1]]
[1] "Yellow"

$`A Inner List`[[2]]
[1] 12.2

In [64]:
# Add element at the end of the list.
list2[4] <- "New Data Added"

# Update the 3rd Element.
list2[3] <- "Updated List"
list2

$`A First Quarter`
[1] "Jan" "Feb" "Mar"

$`A Matrix`
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

$`A Inner List`
[1] "Updated List"

[[4]]
[1] "New Data Added"

# 2-Way Frequency Table

In [65]:
A <- factor(x = c("Male", "Female", "Female", "Male", "Female", "Male"), levels = c("Male", "Female"))
B <- factor(x = c("A", "A", "B", "A", "B", "B"), levels = c("A", "B"))

mytable <- table(A, B)
print(mytable)

        B
A        A B
  Male   2 1
  Female 1 2


In [66]:
'A frequencies (summed over B):'
margin.table(mytable, 1)

'B frequencies (summed over A):'
margin.table(mytable, 2)

'cell percentages:'
prop.table(mytable)

'row percentage:'
prop.table(mytable, 1)

'column percentage:'
prop.table(mytable, 2)

[1] "A frequencies (summed over B):"

A
  Male Female 
     3      3 

[1] "B frequencies (summed over A):"

B
A B 
3 3 

[1] "cell percentages:"

        B
A                A         B
  Male   0.3333333 0.1666667
  Female 0.1666667 0.3333333

[1] "row percentage:"

        B
A                A         B
  Male   0.6666667 0.3333333
  Female 0.3333333 0.6666667

[1] "column percentage:"

        B
A                A         B
  Male   0.6666667 0.3333333
  Female 0.3333333 0.6666667

# Date and Time Functions in R

In [67]:
# Show Current Date

'Date:'
date()

'System time:'
Sys.time()

'System Date:'
Sys.Date()

# Show their Class
class(date())
class(Sys.time())
class(Sys.Date())

[1] "Date:"

[1] "Wed Nov 29 15:21:28 2023"

[1] "System time:"

[1] "2023-11-29 15:21:28 UTC"

[1] "System Date:"

[1] "2023-11-29"

[1] "character"

[1] "POSIXct" "POSIXt"

[1] "Date"

# Reding Data

In [68]:
df = read.csv("/kaggle/input/nifty50-stock-market-data/ADANIPORTS.csv")
df

Date       Symbol     Series Prev.Close Open    High    Low     Last   
1    2007-11-27 MUNDRAPORT EQ      440.00     770.00 1050.00  770.00  959.00
2    2007-11-28 MUNDRAPORT EQ      962.90     984.00  990.00  874.00  885.00
3    2007-11-29 MUNDRAPORT EQ      893.90     909.00  914.75  841.00  887.00
4    2007-11-30 MUNDRAPORT EQ      884.20     890.00  958.00  890.00  929.00
5    2007-12-03 MUNDRAPORT EQ      921.55     939.75  995.00  922.00  980.00
6    2007-12-04 MUNDRAPORT EQ      969.30     985.00 1056.00  976.00 1049.00
7    2007-12-05 MUNDRAPORT EQ     1041.45    1061.00 1099.50 1050.00 1084.00
8    2007-12-06 MUNDRAPORT EQ     1082.45    1089.00 1109.70 1051.00 1090.10
9    2007-12-07 MUNDRAPORT EQ     1081.30    1100.00 1134.00 1078.00 1100.00
10   2007-12-10 MUNDRAPORT EQ     1102.40    1110.00 1110.00 1061.10 1073.55
11   2007-12-11 MUNDRAPORT EQ     1075.40    1081.00 1089.00 1041.00 1046.00
12   2007-12-12 MUNDRAPORT EQ     1047.65    1032.00 1065.00 1016.00 1036.90
13   2007-12-13 MUNDRAPORT EQ     1036.80    1040.00 1150.00 1030.25 1131.15
14   2007-12-14 MUNDRAPORT EQ     1129.95    1139.90 1140.00 1101.10 1107.00
15   2007-12-17 MUNDRAPORT EQ     1110.50    1140.00 1168.00 1021.50 1052.00
16   2007-12-18 MUNDRAPORT EQ     1044.25    1045.00 1109.90 1031.55 1085.00
17   2007-12-19 MUNDRAPORT EQ     1074.95    1091.00 1116.00 1046.30 1078.00
18   2007-12-20 MUNDRAPORT EQ     1066.90    1083.50 1083.50 1051.00 1067.00
19   2007-12-24 MUNDRAPORT EQ     1060.20    1095.00 1192.00 1085.25 1160.00
20   2007-12-26 MUNDRAPORT EQ     1156.80    1175.00 1214.00 1148.00 1212.00
21   2007-12-27 MUNDRAPORT EQ     1199.90    1215.00 1240.00 1204.00 1209.00
22   2007-12-28 MUNDRAPORT EQ     1211.65    1189.40 1274.00 1175.00 1270.00
23   2007-12-31 MUNDRAPORT EQ     1249.10    1263.35 1295.00 1261.00 1268.00
24   2008-01-01 MUNDRAPORT EQ     1268.80    1279.00 1319.00 1263.70 1308.00
25   2008-01-02 MUNDRAPORT EQ     1296.85    1310.25 1324.00 1270.00 1300.15
26   2008-01-03 MUNDRAPORT EQ     1307.45    1305.00 1314.70 1261.15 1267.15
27   2008-01-04 MUNDRAPORT EQ     1275.80    1278.80 1294.80 1233.00 1239.90
28   2008-01-07 MUNDRAPORT EQ     1240.35    1240.00 1278.90 1215.00 1233.00
29   2008-01-08 MUNDRAPORT EQ     1227.25    1240.00 1255.00 1185.00 1202.00
30   2008-01-09 MUNDRAPORT EQ     1204.80    1200.00 1210.00 1151.00 1181.00
⋮    ⋮          ⋮          ⋮      ⋮          ⋮       ⋮       ⋮       ⋮      
3293 2021-03-16 ADANIPORTS EQ     719.05     731.40  735.70  714.25  715.50 
3294 2021-03-17 ADANIPORTS EQ     717.35     715.00  716.95  683.80  686.00 
3295 2021-03-18 ADANIPORTS EQ     688.25     695.00  705.50  675.40  680.90 
3296 2021-03-19 ADANIPORTS EQ     679.65     677.40  691.50  657.10  688.00 
3297 2021-03-22 ADANIPORTS EQ     686.25     686.00  726.25  681.00  721.95 
3298 2021-03-23 ADANIPORTS EQ     721.90     730.25  755.00  727.10  736.75 
3299 2021-03-24 ADANIPORTS EQ     738.55     741.00  750.50  697.65  708.15 
3300 2021-03-25 ADANIPORTS EQ     706.85     711.00  712.35  683.15  687.60 
3301 2021-03-26 ADANIPORTS EQ     688.25     698.00  710.70  692.60  702.00 
3302 2021-03-30 ADANIPORTS EQ     703.05     703.05  718.00  697.30  710.00 
3303 2021-03-31 ADANIPORTS EQ     710.55     705.00  719.90  698.60  702.40 
3304 2021-04-01 ADANIPORTS EQ     702.40     713.50  742.00  705.00  733.55 
3305 2021-04-05 ADANIPORTS EQ     736.25     731.75  745.00  715.00  744.00 
3306 2021-04-06 ADANIPORTS EQ     742.25     756.00  852.70  743.00  849.85 
3307 2021-04-07 ADANIPORTS EQ     835.55     857.00  885.00  795.00  812.45 
3308 2021-04-08 ADANIPORTS EQ     814.75     818.00  838.00  806.00  824.00 
3309 2021-04-09 ADANIPORTS EQ     823.00     824.75  837.00  817.05  822.20 
3310 2021-04-12 ADANIPORTS EQ     823.60     809.90  809.90  735.00  750.00 
3311 2021-04-13 ADANIPORTS EQ     744.65     750.00  755.75  701.35  733.10 
3312 2021-04-15 ADANIPORTS EQ     731.05     735.90  754.50  725.00  747.00 
3

In [69]:
df['Close']
# df$Close

Close_price_df <- df$Close

Close  
1     962.90
2     893.90
3     884.20
4     921.55
5     969.30
6    1041.45
7    1082.45
8    1081.30
9    1102.40
10   1075.40
11   1047.65
12   1036.80
13   1129.95
14   1110.50
15   1044.25
16   1074.95
17   1066.90
18   1060.20
19   1156.80
20   1199.90
21   1211.65
22   1249.10
23   1268.80
24   1296.85
25   1307.45
26   1275.80
27   1240.35
28   1227.25
29   1204.80
30   1180.25
⋮    ⋮      
3293 717.35 
3294 688.25 
3295 679.65 
3296 686.25 
3297 721.90 
3298 738.55 
3299 706.85 
3300 688.25 
3301 703.05 
3302 710.55 
3303 702.40 
3304 736.25 
3305 742.25 
3306 835.55 
3307 814.75 
3308 823.00 
3309 823.60 
3310 744.65 
3311 731.05 
3312 750.35 
3313 755.50 
3314 720.95 
3315 720.45 
3316 737.80 
3317 725.35 
3318 730.75 
3319 749.15 
3320 746.25 
3321 746.75 
3322 730.05

In [70]:
sapply(Close_price_df, mean, na.rm = FALSE)
'Summary:'
summary(Close_price_df)
'Five Number:'
fivenum(Close_price_df)

[1]  962.90  893.90  884.20  921.55  969.30 1041.45 1082.45 1081.30 1102.40
  [10] 1075.40 1047.65 1036.80 1129.95 1110.50 1044.25 1074.95 1066.90 1060.20
  [19] 1156.80 1199.90 1211.65 1249.10 1268.80 1296.85 1307.45 1275.80 1240.35
  [28] 1227.25 1204.80 1180.25 1121.55 1085.85 1035.15 1049.55 1030.40 1020.90
  [37]  994.60  825.05  735.55  857.00  814.15  865.70  820.80  840.75  830.45
  [46]  837.65  825.35  856.10  834.30  807.50  796.25  784.05  711.20  681.30
  [55]  670.95  709.80  728.75  771.60  763.90  732.10  737.60  724.00  707.65
  [64]  735.80  746.40  737.75  735.65  699.25  669.25  640.90  609.75  601.15
  [73]  623.70  602.90  566.30  561.00  511.45  502.40  497.75  469.20  497.15
  [82]  504.05  516.00  619.20  578.75  592.20  608.35  602.30  593.20  593.40
  [91]  589.65  597.75  608.60  610.20  642.55  637.40  626.35  645.15  665.85
 [100]  666.70  665.25  712.15  736.45  740.60  760.15  766.65  754.40  757.90
 [109]  768.50  781.50  783.75  807.55  792.85  789.20  790.85  775.60  884.05
 [118]  901.35  884.40  853.65  887.45  873.05  841.00  834.85  790.40  765.80
 [127]  739.40  702.20  657.55  639.60  612.60  589.25  607.10  593.50  600.30
 [136]  620.90  630.60  628.90  649.15  624.25  571.05  568.70  549.70  528.45
 [145]  496.00  494.15  478.15  481.30  443.35  450.40  467.35  459.45  551.35
 [154]  567.75  546.35  534.90  488.00  478.20  478.75  467.40  476.35  516.45
 [163]  553.55  584.60  587.80  588.45  554.70  563.90  578.00  576.25  585.05
 [172]  587.00  576.65  573.75  581.55  591.00  626.50  614.75  572.30  573.75
 [181]  568.90  580.15  564.35  575.90  582.20  568.65  560.80  557.55  577.25
 [190]  591.05  590.65  583.80  570.75  580.15  580.45  589.65  579.60  562.75
 [199]  535.75  538.35  493.65  454.75  456.40  443.85  442.55  446.90  439.95
 [208]  430.95  422.85  431.65  434.10  431.85  412.15  415.25  396.75  349.40
 [217]  380.10  398.70  380.40  400.50  401.00  410.00  436.00  420.25  405.30
 [226]  375.40  340.25  364.05  342.65  357.90  355.35  347.30  354.75  348.30
 [235]  341.15  343.25  346.25  339.55  322.85  329.45  324.80  309.80  288.15
 [244]  285.65  280.90  275.40  268.45  257.95  265.65  259.45  262.55  270.30
 [253]  269.40  265.25  279.40  284.25  282.65  293.20  321.05  307.75  314.40
 [262]  320.55  311.70  309.65  312.80  305.45  315.75  319.70  325.30  333.80
 [271]  331.25  390.40  395.20  352.05  338.00  369.85  349.75  384.75  373.10
 [280]  375.45  362.70  375.05  356.55  369.10  363.90  375.70  394.55  381.45
 [289]  386.15  389.60  380.60  368.55  367.90  375.20  385.50  376.45  371.60
 [298]  367.40  368.30  358.55  345.95  334.15  352.00  351.25  346.20  345.25
 [307]  345.10  341.65  316.35  306.60  314.00  310.80  309.80  297.90  297.90
 [316]  311.70  312.20  310.35  326.60  312.65  314.30  322.15  314.30  324.20
 [325]  321.60  308.15  318.10  323.30  340.80  347.25  385.15  365.65  378.30
 [334]  380.10  399.70  380.20  377.00  378.80  379.60  386.80  391.55  403.50
 [343]  389.70  369.50  388.75  405.30  410.55  401.35  411.95  413.20  403.45
 [352]  408.15  438.60  461.95  471.75  523.35  528.75  536.50  559.10  546.30
 [361]  599.80  576.25  589.70  588.50  611.20  651.15  629.00  600.95  620.25
 [370]  626.65  622.25  680.20  687.40  674.80  665.60  630.30  633.55  613.75
 [379]  617.70  619.20  617.85  600.85  612.55  611.40  614.95  634.80  604.10
 [388]  607.80  589.25  585.85  539.85  521.05  505.75  494.80  516.10  506.00
 [397]  525.10  540.15  528.90  543.55  551.75  553.30  555.95  557.25  558.45
 [406]  559.10  561.05  545.85  557.05  601.35  600.75  600.40  597.25  571.30
 [415]  540.35  561.45  547.55  544.55  553.65  552.40  541.95  535.30  530.15
 [424]  530.25  528.80  537.75  542.45  552.95  584.70  569.20  557.50  535.55
 [433]  526.05  546.15  550.20  567.95  544.55  540.15  540.35  534.00  535.20
 [442]  547.25  539.95  534.95  535.25  542.65  537.50  531.70  528.45  526.00
 [451]  519.85  525.55  514.80  510.95  510.50  525.2

[1] "Summary:"

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  108.0   164.3   324.7   344.2   400.9  1307.5 

[1] "Five Number:"

[1]  108.00  164.30  324.70  400.95 1307.45

In [71]:
install.packages("Hmisc")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message:
“dependency ‘htmlTable’ is not available”
Warning message in install.packages("Hmisc"):
“installation of package ‘Hmisc’ had non-zero exit status”


In [72]:
# library(Hmisc)
# describe(df)

In [73]:
install.packages("pastecs")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [74]:
library(pastecs)
stat.desc(df)

Date Symbol Series Prev.Close   Open         High         Low         
nbr.val  NA   NA     NA     3.322000e+03 3.322000e+03 3.322000e+03 3.322000e+03
nbr.null NA   NA     NA     0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
nbr.na   NA   NA     NA     0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
min      NA   NA     NA     1.080000e+02 1.080000e+02 1.104500e+02 1.056500e+02
max      NA   NA     NA     1.307450e+03 1.310250e+03 1.324000e+03 1.270000e+03
range    NA   NA     NA     1.199450e+03 1.202250e+03 1.213550e+03 1.164350e+03
sum      NA   NA     NA     1.143148e+06 1.145303e+06 1.168042e+06 1.121281e+06
median   NA   NA     NA     3.247000e+02 3.257500e+02 3.312750e+02 3.198500e+02
mean     NA   NA     NA     3.441143e+02 3.447630e+02 3.516080e+02 3.375320e+02
SE.mean  NA   NA     NA     3.347460e+00 3.359312e+00 3.446025e+00 3.273545e+00
CI.mean  NA   NA     NA     6.563294e+00 6.586532e+00 6.756547e+00 6.418369e+00
var      NA   NA     NA     3.722464e+04 3.748870e+04 3.944903e+04 3.559886e+04
std.dev  NA   NA     NA     1.929369e+02 1.936200e+02 1.986178e+02 1.886766e+02
coef.var NA   NA     NA     5.606767e-01 5.616031e-01 5.648842e-01 5.589889e-01
         Last         Close        VWAP         Volume       Turnover    
nbr.val  3.322000e+03 3.322000e+03 3.322000e+03 3.322000e+03 3.322000e+03
nbr.null 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
nbr.na   0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
min      1.080000e+02 1.080000e+02 1.083400e+02 1.236600e+04 2.415857e+11
max      1.308000e+03 1.307450e+03 1.302150e+03 9.771788e+07 8.160988e+15
range    1.200000e+03 1.199450e+03 1.193810e+03 9.770551e+07 8.160747e+15
sum      1.143564e+06 1.143438e+06 1.145602e+06 9.815061e+09 3.555019e+17
median   3.250000e+02 3.247000e+02 3.257650e+02 2.007292e+06 5.836041e+13
mean     3.442395e+02 3.442016e+02 3.448532e+02 2.954564e+06 1.070144e+14
SE.mean  3.351814e+00 3.349352e+00 3.363152e+00 7.120845e+04 4.555361e+12
CI.mean  6.571830e+00 6.567002e+00 6.594060e+00 1.396169e+05 8.931598e+12
var      3.732153e+04 3.726671e+04 3.757445e+04 1.684468e+13 6.893585e+28
std.dev  1.931878e+02 1.930459e+02 1.938413e+02 4.104227e+06 2.625564e+14
coef.var 5.612017e-01 5.608512e-01 5.620981e-01 1.389114e+00 2.453467e+00
         Trades       Deliverable.Volume X.Deliverble
nbr.val  2.456000e+03 3.322000e+03       3.322000e+03
nbr.null 0.000000e+00 0.000000e+00       0.000000e+00
nbr.na   8.660000e+02 0.000000e+00       0.000000e+00
min      3.660000e+02 5.383000e+03       6.700000e-02
max      1.205984e+06 2.241652e+07       9.798000e-01
range    1.205618e+06 2.241113e+07       9.128000e-01
sum      1.103299e+08 4.011119e+09       1.481276e+03
median   3.588150e+04 8.132775e+05       4.456500e-01
mean     4.492259e+04 1.207441e+06       4.458987e-01
SE.mean  1.013584e+03 2.426645e+04       2.784612e-03
CI.mean  1.987568e+03 4.757870e+04       5.459729e-03
var      2.523177e+09 1.956194e+12       2.575900e-02
std.dev  5.023124e+04 1.398640e+06       1.604961e-01
coef.var 1.118173e+00 1.158351e+00       3.599385e-01

In [75]:
library(psych)
describe(df)

vars n    mean         sd           median      
Date*               1   3322 1.661500e+03 9.591231e+02 1.661500e+03
Symbol*             2   3322 1.307947e+00 4.617140e-01 1.000000e+00
Series*             3   3322 1.000000e+00 0.000000e+00 1.000000e+00
Prev.Close          4   3322 3.441143e+02 1.929369e+02 3.247000e+02
Open                5   3322 3.447630e+02 1.936200e+02 3.257500e+02
High                6   3322 3.516080e+02 1.986178e+02 3.312750e+02
Low                 7   3322 3.375320e+02 1.886766e+02 3.198500e+02
Last                8   3322 3.442395e+02 1.931878e+02 3.250000e+02
Close               9   3322 3.442016e+02 1.930459e+02 3.247000e+02
VWAP               10   3322 3.448532e+02 1.938413e+02 3.257650e+02
Volume             11   3322 2.954564e+06 4.104227e+06 2.007292e+06
Turnover           12   3322 1.070144e+14 2.625564e+14 5.836041e+13
Trades             13   2456 4.492259e+04 5.023124e+04 3.588150e+04
Deliverable.Volume 14   3322 1.207441e+06 1.398640e+06 8.132775e+05
X.Deliverble       15   3322 4.458987e-01 1.604961e-01 4.456500e-01
                   trimmed      mad          min          max         
Date*              1.661500e+03 1.231299e+03 1.000000e+00 3.322000e+03
Symbol*            1.259970e+00 0.000000e+00 1.000000e+00 2.000000e+00
Series*            1.000000e+00 0.000000e+00 1.000000e+00 1.000000e+00
Prev.Close         3.179432e+02 1.564884e+02 1.080000e+02 1.307450e+03
Open               3.185488e+02 1.553765e+02 1.080000e+02 1.310250e+03
High               3.244094e+02 1.567479e+02 1.104500e+02 1.324000e+03
Low                3.121604e+02 1.542275e+02 1.056500e+02 1.270000e+03
Last               3.180088e+02 1.565996e+02 1.080000e+02 1.308000e+03
Close              3.180138e+02 1.564884e+02 1.080000e+02 1.307450e+03
VWAP               3.185418e+02 1.559399e+02 1.083400e+02 1.302150e+03
Volume             2.254473e+06 2.037264e+06 1.236600e+04 9.771788e+07
Turnover           6.757362e+13 6.496900e+13 2.415857e+11 8.160988e+15
Trades             3.768425e+04 2.346140e+04 3.660000e+02 1.205984e+06
Deliverable.Volume 9.641726e+05 8.531881e+05 5.383000e+03 2.241652e+07
X.Deliverble       4.444902e-01 1.650134e-01 6.700000e-02 9.798000e-01
                   range        skew       kurtosis    se          
Date*              3.321000e+03  0.0000000  -1.2010837 1.664081e+01
Symbol*            1.000000e+00  0.8316627  -1.3087308 8.010751e-03
Series*            0.000000e+00        NaN         NaN 0.000000e+00
Prev.Close         1.199450e+03  1.2745715   2.1158033 3.347460e+00
Open               1.202250e+03  1.2827090   2.1628623 3.359312e+00
High               1.213550e+03  1.3081120   2.2306591 3.446025e+00
Low                1.164350e+03  1.2546276   2.0482408 3.273545e+00
Last               1.200000e+03  1.2790607   2.1375539 3.351814e+00
Close              1.199450e+03  1.2734256   2.1067437 3.349352e+00
VWAP               1.193810e+03  1.2794402   2.1244184 3.363152e+00
Volume             9.770551e+07  7.5931383 117.6161338 7.120845e+04
Turnover           8.160747e+15 14.6388909 340.4060837 4.555361e+12
Trades             1.205618e+06  8.9720880 150.5633590 1.013584e+03
Deliverable.Volume 2.241113e+07  3.9036923  31.1098000 2.426645e+04
X.Deliverble       9.128000e-01  0.1112526  -0.2798369 2.784612e-03